### ISSUE TITLE
Support transforming of unicode emoji's to image based emoji's

### ISSUE THREAD

**Issue by 3rd-Eden** [markdown-it/markdown-it-emoji#10]
Currently it's possible to add "native" unicode emoji's to documents which are differently styled then the `:name:` based emoji's which can lead to a really confusing experience.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-emoji#change-output

Isn't it described in readme?

**Comment by 3rd-Eden** [comment]
I'm arguing that it should be supported by this library natively instead of resorting to writing your own implementations.

**Comment by puzrin** [comment]
I don't like this idea, because there can be different ways of extending. For example, with iconic fonts. It's not good to force user with twitter icons and make plugin dependent on external resources.

**Comment by 3rd-Eden** [comment]
Also, in the example you are given, the `md.renderer.rules.emoji` function isn't even called when passing it an unicode emoji as the plugin only triggers on `:...:` chars, not unicode. But I guess i'll go write my own plugin then.

**Comment by puzrin** [comment]
I think, if you need to replace direct unicode chars, that's a bit another deal, not for this plugin. This plugin was done to work with markup.
