### ISSUE TITLE
Question: How can I escape an emoji string so it's not rendered as emoji?

### ISSUE THREAD

**Issue by muffinresearch** [markdown-it/markdown-it-emoji#11]
I have some text which has strings being detected as a emoji when I don't want them to. Is there a way to escape the emoji syntax?

I was hoping \\:op would render \:op rather than  :open_mouth:

**Comment by puzrin** [comment]
Current implementation is simple, it operates with parser text nodes output, instead of sitting on tokenizer level. So, it can't understand escaping. I'd suggest to select emoji patterns more carefully.

Sometime problem can be solved by improving start/end guard conditions. If it's you case - give me your text example with false positive.

**Comment by muffinresearch** [comment]
I have a string which is reflecting some code e.g: 

```
<em:optionTypes>
```
I get this output instead :)

<img alt="validator_rules" src="https://cloud.githubusercontent.com/assets/1514/10832838/af76795c-7e85-11e5-9e32-056fe9083084.png">

**Comment by muffinresearch** [comment]
I suppose I could easily solve this by surrounding that with "`".

**Comment by puzrin** [comment]
Does "\`" solve your problem or should i think about additional checks, similar to `/w` before/after shourtcuts?

**Comment by muffinresearch** [comment]
Yep - surrounding the code snippet with "`" did indeed solve it for me. I'll let you decide if you want to keep this open but my own issue is resolved. Thanks!

**Comment by puzrin** [comment]
Closing then. Will reopen if anyone decide he has unresolvable problem.

**Comment by bstanleynerd** [comment]
Based on [this post](https://stackoverflow.com/questions/50657698/how-can-i-stop-github-from-rendering-emojis-in-markdown) I was able to resolve this in my case by using the hex encoded character entity for zero-width space: &#8203;  In my case the "8)" portion of "(7 & 8)" was being rendered as the "cool" emoji.  Inserting a zero-width space between the "8" and the right parenthesis did the trick.  Like this:  "(7 & 8&amp;#8203;)".

FWIW, [this post](https://stackoverflow.com/questions/11392312/zero-width-non-breaking-space) mentions other characters that might also do the trick. See the comment by `davidcondrey`.
