### ISSUE TITLE
Extending list of emoji mappings instead of replacing

### ISSUE THREAD

**Issue by rj33** [markdown-it/markdown-it-emoji#12]
Is there an easy way to extend the list of emojies without having to feed in an entire new list? I'd like to supplement the light version with a small number of new items, but couldn't find an obvious way of doing that in the current API. Is there something I'm missing, and if not , would it be possible to add an 'extras' param to the available options?

**Comment by puzrin** [comment]
`require('markdown-it-emoji/lib/data/light.json')` and extend it as you wish.

**Comment by rj33** [comment]
I'm loading via markdown-it-emoji-light.min.js in the browser without a supported package manager, so that doesn't work so well for my use case, which is why I was hoping for an API method of supplementing the existing list instead of replacing it.  In the absence of API support, I guess the easiest method will probably be to rebuild markdown-it-emoji-light.min.js with an updated light.json.

**Comment by puzrin** [comment]
I think it's better to copy data file to your project and modify it as you need. Your request is too specific for api change.
