### ISSUE TITLE
Support Skin Tone

### ISSUE THREAD

**Issue by crookedneighbor** [markdown-it/markdown-it-emoji#15]
Some emojis have skin tone variants. Slack, for instance, supports them like this:

```
:+1::skin-tone-2:

**Comment by puzrin** [comment]
I'm very conservative about adding features, not existing in specifications. In theory, i could accept PR, if someone can explain how wide this extension is used and why is it good for all.

**Comment by puzrin** [comment]
Close as "strange / no feedback"
