### ISSUE TITLE
Typings / typescript support?

### ISSUE THREAD

**Issue by tchoulihan** [markdown-it/markdown-it-emoji#16]
I'm unable to use this in typescript, while I am able to use 'markdown-it'. Is there any chance we'll get some typings for this, or at least a way to use this from the already typed markdown-it?

**Comment by puzrin** [comment]
We do not use typescript and can't help with it. If you can explain what's wrong with this package we will fix it.

**Comment by tchoulihan** [comment]
Figured it out! Basically I was finding that when I used `this.markdownIt.use(window.markdownitEmoji);`, it was throwing typescript errors, saying it couldn't find that variable on the window, and I thought that typings would be necessary. 

Using `markdownIt.use(markdownitEmoji);` seems to work fine.

**Comment by rhysd** [comment]
I found this issue for the same purpose.

And I also found that type definitions for markdown-it is contributed to DefinitelyTyped.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/markdown-it/index.d.ts

Just for your info.
