### ISSUE TITLE
Support glyphs icons

### ISSUE THREAD

**Issue by Psychokrameur** [markdown-it/markdown-it-emoji#17]
Hello,

How can I add some feature to your plugin to be able to use Fontawesome or Glyphicon Glyphs in the mardown syntax?

I've seen [mardown-it-icon](https://github.com/tylingsoft/markdown-it-icon) plugin which provide this ability (with some rewrite) but it's a fork of your plugin based on an old version, and the logic seems different...

Thanks in advance

**Comment by puzrin** [comment]
You can define any mapping you wish. You question is too abstract. I'd suggest to look into code, it's very simple.
