### ISSUE TITLE
A performance improvement

### ISSUE THREAD

**Issue by tylerlong** [markdown-it/markdown-it-emoji#22]
I think it's OK to `return` at this line:
https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/replace.js#L77

Because this line will never be true once the line above is true:
https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/replace.js#L80

By `return`, we can save lots of loop time, thus performance benefits from it.

**Comment by tylerlong** [comment]
Oops, could `token.nesting` be zero or even negative?

**Comment by puzrin** [comment]
Yes, it can.

Also, abstract optimization requests are not accepted without benchmarcs. Everything is already good enougth for real world.
