### ISSUE TITLE
Window object

### ISSUE THREAD

**Issue by mikenils** [markdown-it/markdown-it-emoji#23]
> *Differences in browser.* If you load the script directly into the page without using a package system, the module will add itself globally with the name `markdownitEmoji`. Init code will look a bit different in this case:
>
>     var md = window.markdownit().use(window.markdownitEmoji);

Is it really necessary to specify `window` object here? Works fine without it:

    var md = markdownit().use(window.markdownitEmoji);

**Comment by puzrin** [comment]
Do as you wish.

**Comment by mikenils** [comment]
I just wanted to know what is better

**Comment by puzrin** [comment]
I don't know. This is programming question how to access global vars, not related to this repo.
