### ISSUE TITLE
Why not use gemoji directly from NPM?

### ISSUE THREAD

**Issue by niftylettuce** [markdown-it/markdown-it-emoji#28]
<https://www.npmjs.com/package/gemoji>

**Comment by puzrin** [comment]
That package is unofficial, i did not know about it. Anyway, we should regenerate light set and more compact full set. What kind of improvement do you expect?

**Comment by niftylettuce** [comment]
I think it is the closest we'll get to the official GitHub gemoji package (Ruby-based) -- per the docs here <https://github.com/wooorm/gemoji#data> it specifies that the data is crawled from the official repo; so it should be very accurate and update to date.  It also looks well maintained too.

Perhaps swap out our usage of the emojis (hard-coded JSON files) with this package?

**Comment by puzrin** [comment]
1. It includes hardcoded data. All updates are done manually. This package also has script to update data in manual mode.
2. In theory, it's possible to update data on install, but this package also includes browserified scripts, and i have no idea how to change those after publish.

Anyway, if you are not satisfied with existing data, you can load your own, that's supported.

**Comment by niftylettuce** [comment]
Completely understand your comments here - though do you agree that with the Node.js philosophy we should use a package that already does this (and is widely used)? That way the only thing you have to focus on with this package is its core functionality (integration with `markdown-it`).

**Comment by niftylettuce** [comment]
In other words - we could delete lines of code in this project - since its already handled for us in another package, that'd be nice!.

**Comment by niftylettuce** [comment]
Also - if this helps further with my argument, `gemoji` has zero dependencies in itself - so it's basically a component of what you already created, but perhaps with a nice API.

**Comment by puzrin** [comment]
My approach is very simple - if package works, any changes without obvious profit are a waste of time :) .
I'd suggest to drop all arguments about "proper programming" and check if you still have something left. If you can explain profit after that - we can discuss it. Please, understand me right - i have too many packages to support and don't like to change those just for fun. Only when significant reasons exist.

**Comment by niftylettuce** [comment]
> I'd suggest to drop all arguments about "proper programming" and check if you still have something left.

Yeah, it's simple - you can cut out a ton of code and you can use a package everyone else does for GitHub emojis on NPM = less code to worry about (you said it yourself- "too many packages to support").

🎉 🌮 :octocat:

**Comment by puzrin** [comment]
That will not change anything in maintenance, because i still need run script to generate json files. It doesn't matter, where data source is - in github repo or in npm dependency.
