### ISSUE TITLE
Links Converted to Emoji

### ISSUE THREAD

**Issue by pnewell** [markdown-it/markdown-it-emoji#32]
I'm having an issue with the following:

`[https://api.sailthru.com](https://api.sailthru.com)`

This gets converted to:

`<a href="https://api.sailthru.com">https:😕/api.sailthru.com</a>`

**Comment by puzrin** [comment]
[Can not reproduce](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Bhttps%3A%2F%2Fapi.sailthru.com%5D%28https%3A%2F%2Fapi.sailthru.com%29%5Cn%5Cn%3A%2F%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).
