### ISSUE TITLE
Gemoji lacks behind

### ISSUE THREAD

**Issue by Crissov** [markdown-it/markdown-it-emoji#33]
Gemoji is rarely updated and still does not support Unicode 10.0, released in June 2017. github/gemoji#139
Consider to switch to [Emojione](https://github.com/emojione/emojione/blob/master/emoji.json) or [Emojidata](https://github.com/iamcal/emoji-data/blob/master/emoji.json) instead. Twemoji and Noto Emoji do not provide an `emoji.json` with short codes, but there may be others that are kept up to date.

**Comment by dessalines** [comment]
I recently had to update this, to be compatible with twemoji. A bunch of new ones were missing, and a bunch of old ones had wrong short codes. Might be good to list the steps I did here.

goto here: https://unicode.org/emoji/charts/full-emoji-list.html

Open console, do

```
(function () {
  const script = document.createElement('script');
  script.onload = () => {
    const emoji = {};
    for (const code of document.querySelectorAll('td.code')) {
      const desc = underscored(code.parentElement.lastElementChild.textContent);
      let key = '';
      code.textContent.trim().split(' ').forEach(unicode => {
        key += twemoji.convert.fromCodePoint(unicode.replace('U+', ''));
      });
      emoji[desc] = key;
    }
    window.emoji = emoji;
  };
  document.head.appendChild(script).src =
    'https://twemoji.maxcdn.com/v/latest/twemoji.min.js';
  function underscored(desc) {
    return desc.trim().replace(/[ :]+/g, '_');
  }
}());
```

This gets you an object that looks like: 
```
{
  "grinning_face": "😀",
  "grinning_face_with_big_eyes": "😃",
  ...
}
```

Now do 
```
.use(markdownitEmoji, {
  defs: twemojis_from_above
});
```

I got this also working nicely in a zurb/tribute autocomplete dropdown if anyones interested, I can post the code here if anyone wants.

@puzrin it might be good to either add some of these instructions to the twemoji section, or to use the instructions above to update the emoji list so we don't have to rewrite the defs.

**Comment by puzrin** [comment]
Such kind of issues should be limited somehow. This package was done to demonstrate general approach in parser, and provide some minimal smiles set. But i certainly don't wish to maintain growing list of all possible emojies.

**Comment by dessalines** [comment]
@WebReflection just made a package for this, so now you could just rely on this as a dependency: https://github.com/WebReflection/emoji-short-name

**Comment by WebReflection** [comment]
FYI current module offers `{"😀": "grinning face"}` as `code => CLRD Short Name`, if you need to have other way around map simply do the following:

```js
const esn = require('emoji-short-name');
const solved = Object.keys(esn).reduce(
  (p, k) => {
    p[esn[k].replace(/[ :]+/g, '_')] = k;
    return p;
  },
  {}
);
```

That's pretty much it, the `solved` object now has your flavor mapped.

> i certainly don't wish to maintain growing list of all possible emojies.

neither do I, which is why `emoji-short-name` is generated automatically via electron so that whenever unicode releases new emoji (I'm member/subscribed there) I build new version and publish.

In this way nobody needs to bother their heavy page and, if I forget to update every 6 months, just ping me to run the build and publish.

**Comment by puzrin** [comment]
I think, it would be enougth if someone add to readme example of `emoji-short-name` use.

**Comment by WebReflection** [comment]
just FYI since _emoji-short-name_ was crawling the whole unicode full emoji list page but not collecting enough info, I've also created [emoji-essential](https://github.com/WebReflection/emoji-essential), used by _emoji-short-name_ itself, which has all the info such as groups and sub-groups of all emoji.

**Comment by puzrin** [comment]
In 2.0.0:

- has clean `bare.js`, to populate from scrach
- updated to latest gemoji DB

---

Is this issue still actual? As i said, this package is not intended to collect all possible emojis. But i could add examples to readme, how to use foreign db packages.

**Comment by sovushka-utrom** [comment]
That would be nice, as even the demo page of markdown-it shows some missing emojis:
![image](https://user-images.githubusercontent.com/50709991/103879323-fd223400-50d7-11eb-8628-25a3450beafc.png)
