### ISSUE TITLE
Support for new emojis like :octocat:

### ISSUE THREAD

**Issue by vaibhav1192** [markdown-it/markdown-it-emoji#35]
Some of the emojis mentioned in github's emojis list(https://gist.github.com/rxaviers/7360908) doesn't work with this library. Eg `:octocat:`(:octocat:), `:partly_sunny`(:partly_sunny:)

**Comment by puzrin** [comment]
Take a look into page source. Those are non-standard extensions, without unicode chars, injected as images. That does not fit into current package simple concept. It's impossible to provide universal solution, when unicode emoji chars are mixed with bitmaps.
