### ISSUE TITLE
Linkify + :x: in URL fails

### ISSUE THREAD

**Issue by cunisia** [markdown-it/markdown-it-emoji#36]
Hello there,

First of al, thanks you very much for taking care of this library, it's very useful 😃

When rendering a Sharepoint URL such as: `https://morningtrans.sharepoint.com/:x:/r/quality/Shared%20Documents/...?d=w119ebfd3d2ee4dea8d7f047b6db59315&csf=1&e=GZRLy`

Mardown-it outputs:
https://morningtrans.sharepoint.com/ ❌/r/quality/Shared%20Documents/...?d=w119ebfd3d2ee4dea8d7f047b6db59315&csf=1&e=GZRLy

Therefore the URL is broken.

**Comment by puzrin** [comment]
[live demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Chttps%3A%2F%2Fmorningtrans.sharepoint.com%2F%3Ax%3A%2Fr%2Fquality%2FShared%2520Documents%2F...%3Fd%3Dw119ebfd3d2ee4dea8d7f047b6db59315%26csf%3D1%26e%3DGZRLy%3E%5Cn%5Cnhttps%3A%2F%2Fmorningtrans.sharepoint.com%2F%3Ax%3A%2Fr%2Fquality%2FShared%2520Documents%2F...%3Fd%3Dw119ebfd3d2ee4dea8d7f047b6db59315%26csf%3D1%26e%3DGZRLy%5Cn%5Cn%3Ax%3A%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

I don't know what version you use, but latest one has no problem about this emoji.

What about `/...?` sequence - this should be repored to `linkify-it` tracker, to discuss how often this can happen. As quick-fix, i'd suggest use `< >` for all miss-linkified texts.
