### ISSUE TITLE
Missing some Github emojis

### ISSUE THREAD

**Issue by privatenumber** [markdown-it/markdown-it-emoji#39]
Says in the README that the full set has all Github supported emojis, but I'm finding that some of then aren't included.

Missing emojis I encountered so far:
`:monocle_face:` -> :monocle_face: 
`:ringed_planet:` -> :ringed_planet:

**Comment by waptik** [comment]
I can confirm it. Some of GitHub's emojies in the big lists don't work.

**Comment by puzrin** [comment]
I've updated DB. But note, this package is about "parse". It doesn't track every src db change.

In 2.0.0 you can take "bare.js" and populate it as you wish.

**Comment by waptik** [comment]
> I've updated DB. But note, this package is about "parse". It doesn't track every src db change.
> 
> In 2.0.0 you can take "bare.js" and populate it as you wish.

Thanks for updating the DB, I updated the pkg in my project as well. Will the README file be updated in regards to extending the package using "bare.js"?

**Comment by puzrin** [comment]
`bare.js` is mentioned in readme. IMO no more updates needed. But you can suggest PR with with your vision of docs.

**Comment by waptik** [comment]
I saw mentioned but nothing more. Okay, i'll play with it and if i come up with something useful , i'll do a PR.
Thanks again for the hard work!
