### ISSUE TITLE
linkify + emoji fails

### ISSUE THREAD

**Issue by jonathanong** [markdown-it/markdown-it-emoji#4]
test case:

```js
'use strict';

var assert = require('assert');

var md = require('markdown-it')({
  linkify: true
});

md.use(require('markdown-it-emoji'));

describe('Linkify', function () {
  it('should linkify URLs', function () {
    var html = md.render('https://github.com');
    assert.equal(html.trim(), '<p><a href="https://github.com">https://github.com</a></p>');
  });
});
```

result:

```html
<p><a href=\"https://github.com\">https❓/github.com</a></p>
```

**Comment by crookedneighbor** [comment]
This also fails for urls that include emoji like shortcuts in them. For instance:

The URL in the message is http://habitica.wikia.com/wiki/Special:Preferences but it displays as http://habitica.wikia.com/wiki/Special😛references

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/markdown-it-emoji/commit/79fe7293850abd63f61e5e96192ce8247937b347

**Comment by cunisia** [comment]
Hello there,

First of al, thanks you very much for taking care of this library, it's very useful 😃 

I managed to reproduce this bug with Sharepoint URL: `https://morningtrans.sharepoint.com/:x:/r/quality/Shared%20Documents/...?d=w119ebfd3d2ee4dea8d7f047b6db59315&csf=1&e=GZRLy` 
is displayed as:
 https://morningtrans.sharepoint.com/:x:/r/quality/Shared%20Documents/...?d=w119ebfd3d2ee4dea8d7f047b6db59315&csf=1&e=GZRLy
