### ISSUE TITLE
Missing TypeScript definitions

### ISSUE THREAD

**Issue by Shinigami92** [markdown-it/markdown-it-emoji#40]
![image](https://user-images.githubusercontent.com/7195563/85136234-9de5fa80-b23f-11ea-97b5-ee4930dda999.png)

**Comment by puzrin** [comment]
This is js project, not ts, nothing missed.

**Comment by Shinigami92** [comment]
Related to #16

If you dont want to provide definitions, I can create a PR
Or do you want that I create a PR in https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by puzrin** [comment]
Sine we can no maintain this definition, it's better to keep it aside, in DefinitelyTped.

**Comment by Shinigami92** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45588
