### ISSUE TITLE
Add variant without bundled definitions

### ISSUE THREAD

**Issue by ErikMichelson** [markdown-it/markdown-it-emoji#41]
Currently, one can choose between the "full" emoji-set by using index.js and the light emoji-set by using light.js.
In case of providing custom definitions, you might want to keep the bundle-size low by not importing the unused light.json or full.json data-sets.

I therefore propose the following:
Add a new file "bare.js" (or another name) that is similar to index.js or light.js but does not import the json data-sets.

**Comment by puzrin** [comment]
IMO it's not a big deal to copypaste `light.js` & customize, but if anyone wish to do PR, it will be accepted.
