### ISSUE TITLE
npm install i markdown-it-emoji

### ISSUE THREAD

**Issue by olivsinz** [markdown-it/markdown-it-emoji#49]
Hey everyone

I would like to express my sincere gratitude for the extraordinary work you have done with this package. As a new user of this package, I really appreciate the feature it offers and the way it has simplified my development process.

I just have a question. 

Is this the real command to install

`npm install i markdown-it-emoji`

or

`npm install markdown-it-emoji`

Do we need to install "i"?

Thank you.

**Comment by rlidwka** [comment]
Pretty sure that's a typo.

It's either `npm install markdown-it-emoji` or `npm i markdown-it-emoji` (`i` is shortcut for install).

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-emoji/commit/bdd07260f080e4d3d812928f3eb0b00883e4e71b

Fixed, thanks!
