### ISSUE TITLE
Showing Wrong Emoji

### ISSUE THREAD

**Issue by TangRufus** [markdown-it/markdown-it-emoji#8]
`:ship:` shows as :rocket: 

If you type `:rocket::ship:` on https://markdown-it.github.io, the output is :rocket::rocket:

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-emoji/blob/master/support/update.js#L12

Hm... need to check why original is parsed with error.

**Comment by rlidwka** [comment]
Pushed the wrong thing, re-opening...

**Comment by rlidwka** [comment]
Fixed. Thanks for reporting!
